package com.studlabs.quiz.util;

public class TokenProvider {

    public static final String adminAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW5pc3RyYXRvciIsInVuaXF1ZV9uYW1lIjoiRWNhdGVyaW5hIEFuZHJvbmVzY3UiLCJuYW1laWQiOiJhZG1pbiIsIm5iZiI6MTU2NTE3ODAxOSwiZXhwIjoxNTk1MTgxNjE5LCJpYXQiOjE1NjUxNzgwMTl9.zmZFPVL9VT2mFwmq0FoEeENBzSNsDnVNXiHwzI5xQYc";
    public static final String expiredAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW5pc3RyYXRvciIsInVuaXF1ZV9uYW1lIjoiRWNhdGVyaW5hIEFuZHJvbmVzY3UiLCJuYW1laWQiOiJhZG1pbiIsIm5iZiI6MTU2NTE3ODAxOSwiZXhwIjoxNTkwODE2MTksImlhdCI6MTU2NTE3ODAxOX0.c9Zu6G1zzamwW10q5oEkv3rGdrkHvvhghVoaXa4nHsw";
    public static final String userAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVXNlciIsInVuaXF1ZV9uYW1lIjoiRWNhdGVyaW5hIEFuZHJvbmVzY3UiLCJuYW1laWQiOiJhZG1pbiIsIm5iZiI6MTU2NTE3ODAxOSwiZXhwIjoxNTkwODE2MTksImlhdCI6MTU2NTE3ODAxOX0.-7jj6Nhuto-iZXBufGpAl3O96mdZXzB8cfZWr6fjIXk";
    public static final String nullUniqueNameAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVXNlciIsInVuaXF1ZV9uYW1lIjoiIiwibmFtZWlkIjoiYWRtaW4iLCJuYmYiOjE1NjUxNzgwMTksImV4cCI6MTU5MDgxNjE5LCJpYXQiOjE1NjUxNzgwMTl9.fZkoaqwFJP0s46cQl_Z8HWwuCpRCzCQbIBpe-xuNJnQ";
    public static final String nullNameIdAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW5pc3RyYXRvciIsInVuaXF1ZV9uYW1lIjoiRWNhdGVyaW5hIEFuZHJvbmVzY3UiLCJuYW1laWQiOiIiLCJuYmYiOjE1NjUxNzgwMTksImV4cCI6MTU5MDgxNjE5LCJpYXQiOjE1NjUxNzgwMTl9.elbW8fDzQiFa6KWGdM52aeGnp9YHWAu2XzDBRfG369w";
}
